main: me.notsodelayed.simmygameapi.SimmyGameAPI
name: SimmyGameAPI
description: Simmy's Game API
author: NotSoDelayed
website: https://github.com/NotSoDelayed
version: 1.0-SNAPSHOT
api-version: '1.8'
commands:
  game:
    description: Manages game instances.
    permission: simmygameapi.game.admin
  stats:
    description: View current player statistics in a game.
  queue:
    description: Queues into matchmaking.