main: me.notsodelayed.thenexus.TheNexus
name: TheNexus
description: TheNexus Game
author: NotSoDelayed
website: https://github.com/NotSoDelayed
version: 1.0-SNAPSHOT
api-version: '1.20'
depend:
  - SimmyGameAPI
commands:
  thenexus:
    aliases: tn
  kit:
    aliases: kits